#pragma once

#include "Runtime/Launch/Resources/Version.h"

#define PBRTEXTURELAB_ENGINE_MAJOR ENGINE_MAJOR_VERSION
#define PBRTEXTURELAB_ENGINE_MINOR ENGINE_MINOR_VERSION
#define PBRTEXTURELAB_ENGINE_PATCH ENGINE_PATCH_VERSION

#define PBRTEXTURELAB_UE_VERSION(Major, Minor) ((Major) * 10000 + (Minor) * 100)
#define PBRTEXTURELAB_CURRENT_UE_VERSION PBRTEXTURELAB_UE_VERSION(ENGINE_MAJOR_VERSION, ENGINE_MINOR_VERSION)

#define PBRTEXTURELAB_UE_5_6_OR_LATER (PBRTEXTURELAB_CURRENT_UE_VERSION >= PBRTEXTURELAB_UE_VERSION(5, 6))
#define PBRTEXTURELAB_UE_5_7_OR_LATER (PBRTEXTURELAB_CURRENT_UE_VERSION >= PBRTEXTURELAB_UE_VERSION(5, 7))
#define PBRTEXTURELAB_UE_5_8_OR_LATER (PBRTEXTURELAB_CURRENT_UE_VERSION >= PBRTEXTURELAB_UE_VERSION(5, 8))

// 5.8 added extra MIC editor-only setters that 5.6/5.7 do not declare.
#if PBRTEXTURELAB_UE_5_8_OR_LATER
#define PBRTEXTURELAB_HAS_MIC_DOUBLE_VECTOR_EDITORONLY 1
#define PBRTEXTURELAB_HAS_MIC_PARAMETER_COLLECTION_EDITORONLY 1
#else
#define PBRTEXTURELAB_HAS_MIC_DOUBLE_VECTOR_EDITORONLY 0
#define PBRTEXTURELAB_HAS_MIC_PARAMETER_COLLECTION_EDITORONLY 0
#endif

// Shared Metallic/Roughness contract used by later tasks.
#define PBRTEXTURELAB_PARAM_BaseColorTexture TEXT("BaseColorTexture")
#define PBRTEXTURELAB_PARAM_NormalTexture TEXT("NormalTexture")
#define PBRTEXTURELAB_PARAM_ORMTexture TEXT("ORMTexture")
#define PBRTEXTURELAB_PARAM_HeightTexture TEXT("HeightTexture")
#define PBRTEXTURELAB_PARAM_NormalStrength TEXT("NormalStrength")
#define PBRTEXTURELAB_PARAM_HeightAmount TEXT("HeightAmount")
#define PBRTEXTURELAB_PARAM_UVScale TEXT("UVScale")

#define PBRTEXTURELAB_UV_CHANNEL_INDEX 0
#define PBRTEXTURELAB_UV_PRESET_100 100
#define PBRTEXTURELAB_UV_PRESET_500 500
